# Generated by Django 3.2 on 2021-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('project_name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=150)),
                ('projectFuture', models.TextField(max_length=50)),
                ('project_live', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
