# Generated by Django 3.2 on 2021-04-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_data', models.CharField(max_length=100)),
                ('y_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(upload_to='')),
                ('client_title', models.CharField(max_length=100)),
                ('client_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_title', models.CharField(max_length=100)),
                ('long_title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(max_length=200)),
                ('total_lecture', models.IntegerField()),
                ('total_class', models.IntegerField()),
                ('all_skill', models.TextField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('youtube_link', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=100)),
                ('home_subtitle', models.CharField(max_length=150)),
                ('technology_description', models.TextField()),
                ('video_description', models.FileField(upload_to='')),
                ('video_url', models.TextField(blank=True, null=True)),
                ('total_client', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('project_name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=150)),
                ('projectFuture', models.TextField(max_length=50)),
                ('project_live', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_image', models.ImageField(upload_to='')),
                ('service_name', models.CharField(max_length=50)),
                ('service_description', models.TextField()),
            ],
        ),
    ]
