# Generated by Django 3.2 on 2021-04-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartData',
        ),
        migrations.DeleteModel(
            name='ClientReviews',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='HomeETC',
        ),
        migrations.DeleteModel(
            name='ProjectTable',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
