# Generated by Django 3.2 on 2021-04-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=models.FileField(upload_to='service'),
        ),
    ]
