# Generated by Django 3.2 on 2021-04-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('short_title', models.CharField(max_length=100)),
                ('long_title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(max_length=200)),
                ('total_lecture', models.IntegerField()),
                ('total_class', models.IntegerField()),
                ('all_skill', models.TextField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
