# Generated by Django 3.2 on 2021-04-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(max_length=100)),
                ('home_subtitle', models.CharField(max_length=150)),
                ('technology_description', models.TextField()),
                ('video_description', models.FileField(upload_to='')),
                ('video_url', models.TextField(blank=True, null=True)),
                ('total_client', models.IntegerField()),
            ],
        ),
    ]
