# Generated by Django 3.2 on 2021-04-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210418_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeetc',
            name='video_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
