# Generated by Django 3.2 on 2021-04-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('youtube_link', models.TextField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
