# Generated by Django 3.2 on 2021-04-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreviews',
            name='client_image',
            field=models.ImageField(upload_to='client Image'),
        ),
    ]
